[build]
  command = "npx pnpm i -r --store=node_modules/.pnpm-store && npx pnpm run build"
  publish = "build"

[build.environment]
  NPM_FLAGS="--prefix=/dev/null"

[[plugins]]
  package = "/.netlify/netlify-plugin-pnpm"