<script>
	import { Notification } from '$lib/components/Icons';
	import { Popover } from 'flowbite-svelte';
</script>

<span id="notification" class="text-secondary w-6 h-6 md:w-10 md:h-10">
	<Notification />
</span>

<Popover
	triggeredBy="#notification"
	class="w-72 text-sm font-light text-gray-500 bg-white dark:bg-gray-800 dark:border-gray-600 dark:text-gray-400"
	placement="bottom-start"
>
	<div class="p-3 space-y-2">
		<h3 class="font-semibold text-gray-900 dark:text-white">Activity growth - Incremental</h3>
		Report helps navigate cumulative growth of community activities. Ideally, the chart should have a
		growing trend, as stagnating chart signifies a significant decrease of community activity.
		<h3 class="font-semibold text-gray-900 dark:text-white">Calculation</h3>
		For each date bucket, the all-time volume of activities is calculated. This means that activities
		in period n contain all activities up to period n, plus the activities generated by your community
		in period.
		<a
			href="/"
			class="flex items-center font-medium text-blue-600 dark:text-blue-500 dark:hover:text-blue-600 hover:text-blue-700"
			>Read more</a
		>
	</div>
</Popover>
